/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ImportantInformationRouteImport } from './routes/important-information'
import { Route as OtpcTermsRouteImport } from './routes/otpc-terms'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as RefundCancellationRouteImport } from './routes/refund-cancellation'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportantInformationRoute = ImportantInformationRouteImport.update({
  id: '/important-information',
  path: '/important-information',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpcTermsRoute = OtpcTermsRouteImport.update({
  id: '/otpc-terms',
  path: '/otpc-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundCancellationRoute = RefundCancellationRouteImport.update({
  id: '/refund-cancellation',
  path: '/refund-cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/games': typeof GamesRoute
  '/important-information': typeof ImportantInformationRoute
  '/otpc-terms': typeof OtpcTermsRoute
  '/plans': typeof PlansRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/games': typeof GamesRoute
  '/important-information': typeof ImportantInformationRoute
  '/otpc-terms': typeof OtpcTermsRoute
  '/plans': typeof PlansRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/casino': typeof CasinoRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/games': typeof GamesRoute
  '/important-information': typeof ImportantInformationRoute
  '/otpc-terms': typeof OtpcTermsRoute
  '/plans': typeof PlansRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/casino'
    | '/contact'
    | '/gallery'
    | '/games'
    | '/important-information'
    | '/otpc-terms'
    | '/plans'
    | '/refund-cancellation'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/casino'
    | '/contact'
    | '/gallery'
    | '/games'
    | '/important-information'
    | '/otpc-terms'
    | '/plans'
    | '/refund-cancellation'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/casino'
    | '/contact'
    | '/gallery'
    | '/games'
    | '/important-information'
    | '/otpc-terms'
    | '/plans'
    | '/refund-cancellation'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRoute
  CasinoRoute: typeof CasinoRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GamesRoute: typeof GamesRoute
  ImportantInformationRoute: typeof ImportantInformationRoute
  OtpcTermsRoute: typeof OtpcTermsRoute
  PlansRoute: typeof PlansRoute
  RefundCancellationRoute: typeof RefundCancellationRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/important-information': {
      id: '/important-information'
      path: '/important-information'
      fullPath: '/important-information'
      preLoaderRoute: typeof ImportantInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otpc-terms': {
      id: '/otpc-terms'
      path: '/otpc-terms'
      fullPath: '/otpc-terms'
      preLoaderRoute: typeof OtpcTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-cancellation': {
      id: '/refund-cancellation'
      path: '/refund-cancellation'
      fullPath: '/refund-cancellation'
      preLoaderRoute: typeof RefundCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRoute,
  CasinoRoute: CasinoRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GamesRoute: GamesRoute,
  ImportantInformationRoute: ImportantInformationRoute,
  OtpcTermsRoute: OtpcTermsRoute,
  PlansRoute: PlansRoute,
  RefundCancellationRoute: RefundCancellationRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
